name: Publish the Package onto PyPI

on:
  release:
    - published
  workflow_call:
    inputs:
      env_yml:
        default: ./.github/workflows/env.yml
        type: string

jobs:
  runs-on: ubuntu-latest
  setenv:
    uses: ./.github/workflows/env.yml
  deploy:
    needs: setenv
    uses: ./.github/workflows/test_n_lint.yml
    with:
      package_name: ${{ needs.setenv.outputs.package_name }}
      requirements: '${{ needs.setenv.outputs.requirements }} build'
  build:
    steps:
    - name: Build Package
      run: python -m build
  publish:
    steps:
    - name: Publish Package on PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
