name: Publish the Package onto PyPI

on:
  release:
    types:
    - published
  workflow_call:
    inputs:
      env_yml:
        default: ./.github/workflows/env.yml
        type: string

jobs:
  setenv:
    uses: ./.github/workflows/env.yml
  execute:
    name: Prepare and Publish Package
    needs: setenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/lint_n_test
      with:
        package_name: ${{ needs.setenv.outputs.package_name }}
        requirements: ${{ format('{0} build', needs.setenv.outputs.requirements) }}'
    - name: Build Package
      run: python -m build
    - name: Publish Package on PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
