name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      env_yml:
        default: ./.github/workflows/env.yml
        type: string

jobs:
  setenv:
    uses: ./.github/workflows/env.yml
  prepare:
    name: Prepare Package
    needs: setenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/lint_n_test
      with:
        package_name: ${{ needs.setenv.outputs.package_name }}
        requirements: ${{ format('{0} build', needs.setenv.outputs.requirements) }}
  build:
    name: Prepare Package
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Build Package
      run: python -m build
  publish:
    name: Publish Package
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy
