name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      env_yml:
        default: ./.github/workflows/env.yml
        type: string

jobs:
  setenv:
    uses: ./.github/workflows/env.yml
  deploy:
    runs-on: ubuntu-latest
    needs: setenv
    steps:
    - uses: ./.github/workflows/test_n_lint.yml
      with:
        package_name: ${{ needs.setenv.outputs.package_name }}
        requirements: '${{ needs.setenv.outputs.requirements }} build'
    - name: Build Package
      run: python -m build
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy
