name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      env_yml:
        default: ./.github/workflows/env.yml
        type: string

jobs:
  setenv:
    uses: ${{ inputs.env_yml }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/lint_n_test.yml
      with:
        package_name: ${{ setenv.outputs.package_name }}
        requirements: '${{ setenv.outputs.requirements }} build'
    - name: Build Package
      run: python -m build
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy
